workspace:
  base: /go
  path: src/github.com/SPSCommerce/registrator
pipeline:
  build_registrator_binary:
    image: alpine:3.7
    environment:
      - VERSION=${DRONE_COMMIT}
    commands:
      - apk --no-cache add -t build-deps build-base go git curl
        && apk --no-cache add ca-certificates
        && export GOPATH=/go && mkdir -p /go/bin && export PATH=$PATH:/go/bin
        && curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        && cd /go/src/github.com/SPSCommerce/registrator
        && export GOPATH=/go
        && git config --global http.https://gopkg.in.followRedirects true
        && dep ensure
        && go build -ldflags "-X main.Version=$(cat VERSION)" -o registrator
    when:
      event:
      - push
      branch:
      - master
  copy_to_s3:
    image: python:3
    commands:
      - pip install awscli
      - aws s3 cp /go/src/github.com/SPSCommerce/registrator/registrator s3://sps-build-deploy/sre/registrator/registrator
    when:
      event:
      - push
      branch:
      - master